### ISSUE TITLE
What VSCode Version to DL extension ? Unable to install 'xamantra.momentum-code' extension because it is not compatible with the current version of VS Code (version 1.41.0)

### ISSUE THREAD

**Issue by Victor-Dev77** [xamantra/momentum-vscode#1]
Hi :)

I try to DL your extension but i've this error when i click on Install btn:
`Unable to install 'xamantra.momentum-code' extension because it is not compatible with the current version of VS Code (version 1.41.0)`

Should I update VSCode ?

Thanks :)

**Comment by xamantra** [comment]
I was able to reproduce this issue. I will dig into it. I think it needs to be built in the lower version of vscode.

**Comment by xamantra** [comment]
@Victor-Dev77 
I uploaded a new version in the [marketplace](https://marketplace.visualstudio.com/items?itemName=xamantra.momentum-code).
Can you try it?

The issue is not your vscode version btw. This is a very simple extension that generates files. It should support lower versions of vscode.

**Comment by Victor-Dev77** [comment]
It works ! Thank you so much mate :)
I discover today your package and I test it. It awesome  🚀
